### ISSUE TITLE
Remove initial left margin on Breadcrumbs component

### ISSUE THREAD

**Issue by vsandvold** [fabric-ds/react#57]
It looks like the `Breadcrumbs` component renders all the links with 8px left margin. In a layout, this breaks the left side alignment with other components. It would look better if left margin was omitted for the first link.

8px left margin:
<img width="395" alt="Skjermbilde 2021-11-21 kl  21 14 43" src="https://user-images.githubusercontent.com/6734787/142777577-73bea9c4-1e0e-4fa0-b2c6-95bae3c3b252.png">

Broken left side alignment in layout:
<img width="95" alt="Skjermbilde 2021-11-21 kl  21 18 48" src="https://user-images.githubusercontent.com/6734787/142777583-f83e9938-8a7e-479c-abde-ab2e66c9272c.png">

**Comment by benja** [comment]
Merged. Will be out in the `0.0.11` release.
